"""
Test Live Trading vs Backtest Comparison
=========================================

Runs the same strategy through both:
1. Traditional backtest engine
2. New modular live trading system

Compares results to validate correctness.
"""

import sys
import os
import json
from datetime import datetime
from pathlib import Path

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

os.environ['SUPABASE_URL'] = 'https://oonepfqgzpdssfzvokgk.supabase.co'
os.environ['SUPABASE_SERVICE_ROLE_KEY'] = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9vbmVwZnFnenBkc3NmenZva2drIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1MDE5OTkxNCwiZXhwIjoyMDY1Nzc1OTE0fQ.qmUNhAh3oVhPW2lcAkw7E2Z19MenEIoWCBXCR9Hq6Kg'

from src.backtesting.backtest_runner import run_backtest
from live_strategy_executor import start_multi_strategy_execution
from src.live_trading import SessionDataLoader
import asyncio


def run_backtest_test(strategy_id: str, user_id: str, test_date: str):
    """Run traditional backtest"""
    print("\n" + "="*80)
    print("RUNNING TRADITIONAL BACKTEST")
    print("="*80)
    
    results = run_backtest(
        strategy_ids=[strategy_id],
        backtest_date=test_date,
        debug_mode=None
    )
    
    print(f"\n✅ Backtest Complete:")
    print(f"   Ticks processed: {results.ticks_processed:,}")
    print(f"   Duration: {results.duration_seconds:.2f}s")
    print(f"   Speed: {results.ticks_processed/results.duration_seconds:.0f} ticks/sec")
    
    return results


async def run_live_trading_test(strategy_id: str, user_id: str, test_date: str):
    """Run new modular live trading system"""
    print("\n" + "="*80)
    print("RUNNING MODULAR LIVE TRADING SYSTEM")
    print("="*80)
    
    # Construct session registry for SessionDataLoader
    session_id = f"{user_id}_{strategy_id}"
    session_registry = {
        session_id: {
            "strategy_id": strategy_id,
            "broker_connection_id": None,  # Use backtesting adapter
            "scale": 1.0,
            "user_id": user_id,
            "enabled": True,
            "execution_date": test_date
        }
    }
    
    # Load session data
    session_loader = SessionDataLoader()
    sessions = session_loader.load_sessions(session_registry)
    
    if not sessions:
        print(f"❌ No sessions loaded for strategy {strategy_id}")
        return None
    
    print(f"\n✅ Loaded {len(sessions)} session(s)")
    for session in sessions:
        print(f"   Session ID: {session.get('session_id')}")
        print(f"   Strategy: {session.get('strategy_config', {}).get('name', 'Unknown')}")
    
    # Run live trading
    start_time = datetime.now()
    await start_multi_strategy_execution(sessions)
    duration = (datetime.now() - start_time).total_seconds()
    
    print(f"\n✅ Live Trading Complete:")
    print(f"   Duration: {duration:.2f}s")
    
    return {
        "sessions": sessions,
        "duration": duration
    }


def compare_results(backtest_results, live_results, strategy_id: str, user_id: str):
    """Compare backtest vs live trading results"""
    print("\n" + "="*80)
    print("COMPARISON: BACKTEST VS LIVE TRADING")
    print("="*80)
    
    # Check event files generated by live trading
    session_id = f"{user_id}_{strategy_id}"
    results_dir = Path(f"live_results/{user_id}/{session_id}")
    
    print(f"\n📁 Live Trading Event Files:")
    if results_dir.exists():
        event_files = list(results_dir.glob("*.jsonl"))
        for event_file in sorted(event_files):
            line_count = sum(1 for _ in open(event_file))
            print(f"   ✅ {event_file.name}: {line_count} events")
            
            # Show sample from each file
            if line_count > 0:
                with open(event_file) as f:
                    sample = json.loads(f.readline())
                    print(f"      Sample: {list(sample.keys())}")
    else:
        print(f"   ❌ Results directory not found: {results_dir}")
    
    print("\n" + "="*80)
    print("VALIDATION CHECKS")
    print("="*80)
    
    # Check 1: Event files exist
    required_files = [
        "events.jsonl",
        "nodes.jsonl", 
        "node_diagnostics.jsonl",
        "trades.jsonl",
        "ticks.jsonl",
        "positions.jsonl",
        "candles.jsonl",
        "ltp.jsonl"
    ]
    
    print("\n1. Required Event Files:")
    for filename in required_files:
        file_path = results_dir / filename
        if file_path.exists():
            line_count = sum(1 for _ in open(file_path))
            print(f"   ✅ {filename}: {line_count} events")
        else:
            print(f"   ❌ {filename}: MISSING")
    
    # Check 2: Snapshot IDs in tick events
    print("\n2. Snapshot ID Synchronization:")
    tick_file = results_dir / "ticks.jsonl"
    if tick_file.exists():
        with open(tick_file) as f:
            lines = f.readlines()
            if len(lines) > 0:
                first_tick = json.loads(lines[0])
                last_tick = json.loads(lines[-1])
                
                print(f"   First tick snapshot IDs: {first_tick.get('latest_snapshot_ids', {})}")
                print(f"   Last tick snapshot IDs: {last_tick.get('latest_snapshot_ids', {})}")
                
                # Validate all 6 snapshot IDs present
                required_ids = ["node", "node_diagnostics", "trade", "position", "candle", "ltp"]
                snapshot_ids = last_tick.get('latest_snapshot_ids', {})
                for id_type in required_ids:
                    if id_type in snapshot_ids:
                        print(f"   ✅ {id_type}: {snapshot_ids[id_type]}")
                    else:
                        print(f"   ❌ {id_type}: MISSING")
    
    # Check 3: Performance comparison
    print("\n3. Performance Comparison:")
    print(f"   Backtest speed: {backtest_results.ticks_processed/backtest_results.duration_seconds:.0f} ticks/sec")
    if live_results:
        print(f"   Live system duration: {live_results['duration']:.2f}s")


def main():
    """Main test runner"""
    
    # Test configuration - using known working strategy from backtest examples
    STRATEGY_ID = '4a7a1a31-e209-4b23-891a-3899fb8e4c28'
    TEST_DATE = '2024-10-29'  # Date with known tick data
    
    # Fetch user_id from strategy
    from supabase import create_client
    supabase = create_client(os.environ['SUPABASE_URL'], os.environ['SUPABASE_SERVICE_ROLE_KEY'])
    result = supabase.table('strategies').select('user_id, name').eq('id', STRATEGY_ID).execute()
    
    if not result.data:
        print(f"❌ Strategy {STRATEGY_ID} not found")
        return
    
    strategy = result.data[0]
    USER_ID = strategy['user_id']
    
    print("\n" + "="*80)
    print("LIVE TRADING VS BACKTEST COMPARISON TEST")
    print("="*80)
    print(f"\nTest Configuration:")
    print(f"   Strategy ID: {STRATEGY_ID}")
    print(f"   Strategy Name: {strategy.get('name', 'Unknown')}")
    print(f"   User ID: {USER_ID}")
    print(f"   Test Date: {TEST_DATE}")
    
    # Run backtest
    backtest_results = run_backtest_test(STRATEGY_ID, USER_ID, TEST_DATE)
    
    # Run live trading
    live_results = asyncio.run(run_live_trading_test(STRATEGY_ID, USER_ID, TEST_DATE))
    
    # Compare results
    compare_results(backtest_results, live_results, STRATEGY_ID, USER_ID)
    
    print("\n" + "="*80)
    print("TEST COMPLETE")
    print("="*80)


if __name__ == "__main__":
    main()
